version: '3.8'

services:
  db:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: youvento
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel_network

  pgadmin:
    container_name: pgadmin4_container_v2
    image: dpage/pgadmin4:9.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - laravel_network

  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./laravel_app:/var/www/html
    ports:
      - "80:80"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres_container
      DB_PORT: 5432
      DB_DATABASE: youvento
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network: